stages:
  - test
  - build

tests:
  stage: test
  script:
    - echo "export PATCH=$CI_BUILD_ID" > PATCH_VERSION
    - apt-get update
    - apt-get install -y --force-yes lsb-release fakeroot
    - pip2 install setuptools find_packages
    - python2 setup.py test
  artifacts:
    paths:
      - ./*.deb
  variables:
    PATCH: $CI_BUILD_ID
  only:
    - dev
    - master

