stages:
  - test
  - build

tests:
  stage: test
  script:
    - echo "export PATCH=$CI_BUILD_ID" > PATCH_VERSION
    - apt-get update -qy
    - apt-get install -y --force-yes lsb-release fakeroot python-dev python-pip
    - pip install -r requirements.txt
    - python setup.py test
  artifacts:
    paths:
      - ./*.deb
  variables:
    PATCH: $CI_BUILD_ID
  only:
    - dev
    - master

