image: alpine:latest

before_script:
  - apt-get update -qy
  - apt-get install -y --force-yes lsb-release fakeroot python-dev python3-dev python3-pip
  - pip3 install -r requirements.txt
  - echo "export PATCH=$CI_BUILD_ID" > PATCH_VERSION

stages:
  - test
  - package
  - upload

# .prep_test: &prep_test |
#   - apt-get update
#   - apt-get install -y --force-yes lsb-release fakeroot python-dev python-pip
#   - pip install -r requirements.txt
#   - echo "export PATCH=$CI_BUILD_ID" > PATCH_VERSION


pages:
  stage: test
  allow_failure: true
  script:
    - cd docs
    - make html
    - mv _build/html/ ../public/
#    - time make cover && mv htmlcov public/
#    - mv docs public/
#    - echo '<html><body><a href="htmlcov/index.html">Test Coverage</a><br/><a href="docs/index.html">Developer Documentation</a></body></html>' > public/index.html
  coverage: '/TOTAL.*?\s+(\d+%)/'
  artifacts:
    paths:
      - public
  only:
    - dev


test:
  stage: test
  script:
    - make test
  variables:
    PATCH: $CI_BUILD_ID
  only:
    - dev
    - master

package:
  stage: package
  script:
    - make package PY_VERSION=3
    - pip3 install dist/*.whl
  artifacts:
    paths:
      - dist
  variables:
    PATCH: $CI_BUILD_ID
  only:
    - master
    - /^v\d+\.\d+(?:.\d+)?(?:-\d+)?$/ # use regexp


upload:
  stage: upload
  script:
    - pip3 install twine
    - twine upload dist/* -u $PYPI_USERNAME -p $PYPI_PASSWORD
  # variables:
  #   PYPI_USERNAME: $CI_BUILD_ID
  only:
    - /^v\d+\.\d+(?:.\d+)?(?:-\d+)?$/ # use regexp
  only:
    - tags

