name: pdbecif documentation

on:
  push:
    branches: 
      - master
      - dev
  pull_request:
    branches: 
      - master
      - dev

jobs:
  documentation:
    name: Generate documentation
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        persist-credentials: false    
    
    - name: Set up python & make docs
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - run: |
        pip install -e .
        pip install -r requirements.txt
        cd docs
        make html
        
    - name: Deploy pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./_build/html
